{
    "A simple example of use is shown below:":"一个简单的使用示例如下所示：",
    "At it\u0027s most basic the {}try{} syntax is as follows:":"最基本的 {}try{} 语法如下：",
    "Finally, you can also nest various {}try{} / {}catch{} / {}finally{} within each other, for example:":"最后，您还可以将各种 {}try{} / {}catch{} / {}finally{} 相互嵌套，例如：",
    "However, having a {}try{} without anything to actually handle any exceptions the code may produce will not be very helpful, so we usually pair it with a {}catch{}, with the following syntax:":"但是，如果 {}try{} 没有任何内容来实际处理代码可能产生的任何异常，将不会很有帮助，因此我们通常将其与 {}catch{} 配对，语法如下：",
    "It is worth noting that you can have any combination of these together, ie:":"值得注意的是，您可以将这些组合在一起，即：",
    "It is worth noting that you can take over the default GML error message and use your own handler code by calling the function {}{}exception_unhandled_handler(){}{}. This {}runtime function{} permits you to supply a custom {}method{} to use that will be called whenever any unhandled exceptions occur in your game.":"值得注意的是，您可以接管默认的 GML 错误消息并通过调用函数 {}{}exception_unhandled_handler(){}{} 使用您自己的处理程序代码。此{}运行时函数{}允许您提供自定义{}方法{}以供您在游戏中发生任何未处理的异常时调用。",
    "It may be that you want to run some code regardless of whether an exception was thrown or not, and so for that you can add in a {}finally{} block. The {}finally{} syntax is:":"您可能希望无论是否抛出异常都运行一些代码，因此您可以添加一个 {}finally{} 块。 {}finally{} 语法是：",
    "Note that within the {}finally{} block you {}cannot {}use {}{}break{}{}, {}{}continue{}{}, {}{}exit{}{} or {}{}return{}{} statements as they have no meaning in this context and the compiler will generate an error if they are used.":"注意，在{}finally{}块中，你{}不能{}使用{}{}break{}{}、{}{}continue{}{}、{}{}exit{}{}或{}{}return{}{}语句，因为它们在这里没有意义，如果使用它们，编译器将产生错误。",
    "The {}try{}, {}catch{} and {}finally{} statements can be used in your game for error checking and permit you to test out blocks of code and control what happens if any {}runtime exceptions{} occur. Using these will prevent the exception ending the game and showing the standard error message to the user, but this means that you will have to handle what happens next in that case, like saving out log files - for example - and ending the game gracefully (note that if you choose to do nothing, your game may become unstable and not perform correctly).":"{}try{}、{}catch{} 和 {}finally{} 语句可在您的游戏中用于错误检查并允许您测试代码块并控制发生任何{}运行时异常{}时发生的情况.使用这些将防止异常结束游戏并向用户显示标准错误消息，但这意味着您将必须处理在这种情况下接下来发生的事情，例如保存日志文件 - 并优雅地结束游戏（请注意，如果您选择什么都不做，您的游戏可能会变得不稳定并且无法正常运行）。",
    "What {}catch{} does is permit you to run extra code supplied in the following block when an exception from the previous {}try{} has been caught. If this is a runtime exception, then the supplied variable can be used to access a {}struct{} which will contain the following information:":"{}catch{} 的作用是允许您在捕获到前一个 {}try{} 的异常时运行以下块中提供的额外代码。如果这是运行时异常，则提供的变量可用于访问包含以下信息的 {}struct{}："
}